version: '3.8'

services:
  gibberish-sender:
    build: .
    image: gibberish:latest
    container_name: gibberish-sender
    volumes:
      - ./data/sender:/data
      - ./config.yaml:/app/config.yaml:ro
    devices:
      - /dev/snd:/dev/snd
    environment:
      - GIBBERISH_ROLE=sender
      - NO_COLOR=0
    stdin_open: true
    tty: true
    command: /bin/bash

  gibberish-receiver:
    build: .
    image: gibberish:latest
    container_name: gibberish-receiver
    volumes:
      - ./data/receiver:/data
      - ./config.yaml:/app/config.yaml:ro
    devices:
      - /dev/snd:/dev/snd
    environment:
      - GIBBERISH_ROLE=receiver
      - NO_COLOR=0
    stdin_open: true
    tty: true
    command: /bin/bash

# Usage:
# 1. Build: docker-compose build
# 2. Start both containers: docker-compose up -d
# 3. Access sender: docker-compose exec gibberish-sender /bin/bash
# 4. Access receiver: docker-compose exec gibberish-receiver /bin/bash
# 5. Stop: docker-compose down
